config/routes.rb
Rails.application.routes.draw do
  root to: 'ducks#index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :ducks do
    resources :rentals
  end
end

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png", class:"rounded-circle" %>
      <strong>RDnD</strong>
    <% end %>
    <h4>All you need is Duck</h4>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <% if !current_user.nil?  %>
        <p><%= current_user.username %></p>
      <% end %>
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
              <%= image_tag "https://img2.freepng.fr/20180427/hlw/kisspng-software-developer-computer-servers-programmer-web-5ae3e3d5ad3b83.0228521815248844377096.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Create a new Duck", new_duck_path, class: "dropdown-item" %>
                <%= link_to "List my ducks", "/ducks?query=#{current_user.username}&commit=Search", class: "dropdown-item" %>
                <%= link_to "My rentals", duck_rentals_path("#{current_user.username}"), class: "dropdown-item"%>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>