config/routes.rb
Rails.application.routes.draw do
  root to: 'ducks#index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :ducks do
    resources :rentals
  end
end

app/models/duck.rb
class Duck < ApplicationRecord
  include PgSearch::Model
  # multisearchable against: [:name, :price]

  pg_search_scope :global_search,
                  against: [ :name, :price ],
                  associated_against:
                  {
                    skills: :name,
                    user: :username
                  },
                  using:
                  {
                    tsearch: { prefix: true }
                    # :trigram
                  }
  # ignoring: :accents

  has_many :rentals
  has_many :favorites, dependent: :destroy
  has_many :duck_skills, dependent: :destroy
  has_many :skills, through: :duck_skills
  has_one_attached :photo
  belongs_to :user
  validates :name, presence: true, length: { minimum: 3 }
  validates :price, presence: true
  validates :description, presence: true, length: { maximum: 1000, too_long: "1000 characters max" }
end

app/controllers/ducks_controller.rb
class DucksController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      sql_query = " \
        ducks.name ILIKE :query \
        OR ducks.price ILIKE :query \
        OR skills.name ILIKE :query \
      "
      @ducks = policy_scope(Duck).global_search(params[:query]).order(updated_at: :desc)

      # @ducks = policy_scope(Duck).select { |duck| duck.skills.include?(Skill.find_by(name: params[:query])) }

    else
      @ducks = policy_scope(Duck).order(updated_at: :desc)
    end

    @markers = @ducks.map do |duck|
      if duck.user.geocoded?
        {
          lat: duck.user.latitude,
          lng: duck.user.longitude,
          info_window: render_to_string(partial: "info_window", locals: { duck: duck }),
          image_url: helpers.asset_url("yellow-duck.png")
        }
      end
    end
  end

  def show
    @duck = Duck.find(params[:id])
    authorize @duck
  end

  def new
    @duck = Duck.new # needed to instantiate the form_for
    authorize @duck
  end

  def create
    @duck = Duck.new(duck_params)
    authorize @duck
    @duck.user = current_user
    @skills_ids = params[:duck][:skills]
    # @duck.skills = @skills.map { |skill| Skill.find_by(id: skill) }
    @skills_ids.each { |id| DuckSkill.create(skill: Skill.find(id), duck: @duck) }
    if @duck.save
      redirect_to duck_path(@duck)
    else
      render :new
    end
  end

  def destroy
    @duck = Duck.find(params[:id])
    authorize @duck
    @duck.destroy
    redirect_to ducks_path
  end

  def edit
    @duck = Duck.find(params[:id])
    authorize @duck
  end

  def update
    @duck = Duck.find(params[:id])
    @duck.update(duck_params)
    authorize @duck
    @skills_ids = params[:duck][:skills]
    if @skills_ids
      @skills_ids.map! { |skill| Skill.find(skill) }
      @duck.skills = @skills_ids
    end
    if @duck.save
      redirect_to duck_path(@duck)
    else
      render :edit
    end
  end

  private

  def duck_params
    params.require(:duck).permit(:name, :skills, :description, :price, :photo)
  end
end

app/views/ducks/_form.html.erb
<div class="container">
  <h2> Add a new duck</h2>
  <hr>
  <%= simple_form_for(@duck) do |f| %>
    <div class="row justify-content-center">
      <div class="col-auto">
          <p>Duck name</p><%= f.input :name , label: false %>
      </div>
      <div class="col-auto">
          <p></p><%= f.input :skills, as: :check_boxes, include_hidden: false, collection: Skill.all, label: false %>
      </div>
      <div class="col-auto">
          <p>Add a photo:</p><%= f.input :photo, as: :file, label: false %>
      </div>
      <div class="col-auto">
          <p>Description:</p><%= f.input :description, label: false %>
      </div>
      <div class="col-auto">
          <p>Price €</p><%= f.input :price, label: false %>
      </div>
      <div>
          <%= f.submit "Confirm", class: "btn btn-flat" %>
      </div>
    </div>
  <% end %>
</div>

app/views/ducks/_info_window.html.erb
<h2><%= duck.name %></h2>
<span><%= duck.price.round %> € - </span>
<span><%= duck.average_rating %> / 5</span>
<p>Owner: <%= duck.user.username %></p>
<p>Address: <%= duck.user.address %></p>

app/views/ducks/edit.html.erb
<h1>Edit duck</h1>
<%= render "form", duck: @duck %>

app/views/ducks/index.html.erb
<div class="container">
  <%= form_tag ducks_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      classe: "form-control",
      placeholder: "Type a language"
    %>
    <%= submit_tag "Search", class: "btn btn-flat" %>
  <% end %>
  <p>Results:<%= @ducks.length %></p>
    <div class="container-row container-with-map">
      <div class="cards">
        <% @ducks.each do |duck| %>
          <div class="card">
            <div class="card-info">
              <h3><%= link_to duck.name, duck_path(duck) %></h3>
              <p>
                <% duck.skills.each do |skill| %>
                  <%= skill.name %>
                <% end %>
              </p>
              <p><% duck.user.username %></p>
            </div>
            <% if duck.photo.attached? %>
              <div class="card-photo">
                <%= cl_image_tag duck.photo.key, height: 200, crop: :fill %>
              </div>
            <% else %>
              <div class="card-photo">
                <%= image_tag "logo.png", height: 200, crop: :fill %>
              </div>
            <% end %>
            <div class="card-row">
              <p><%= duck.price.round %> €/day</p>
              <p><%= duck.average_rating.to_f.round(1)%>/5</p>
            </div>
          </div>
        <% end %>
      </div>
      <div class="container-map">
        <div style="height: 600px;"
          data-controller="mapbox"
          data-mapbox-markers-value="<%= @markers.to_json %>"
          data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
</div>

app/views/ducks/new.html.erb
<h1>Add a new duck</h1>
<%= render "form", duck: @duck %>

app/views/ducks/show.html.erb
<div class="container">
  <div class="show-global">
    <div class="show-description">
      <div>
        <h1>Hi, my name is <%= @duck.name %></h1>
        <p>Trained by: <%= @duck.user.username %></p>
        <br>
        <h3>I can help you with: <% @duck.skills.each do |skill| %>
              <%= skill.name %>
            <% end %>
        </h3>
      </div>
      <div>
      <br>
      <h3>Description:</h3>
      <h4><%= @duck.description %></h4>
      </div>
      <br>
      <div>
        <p><%= @duck.price.round %> €/day</p>
        <p><%= @duck.average_rating.to_f.round(1) %>/5</p>
      </div>
      <div class="show-link">
        <%= link_to "Rent", new_duck_rental_path(@duck.id), class: "btn btn-flat" %>
        <% if policy(@duck).update? %>
          <%= link_to "Edit", edit_duck_path(@duck), class: "btn btn-flat blue" %>
         <% end %>
        <% if policy(@duck).destroy? %>
          <%= link_to 'Delete',
                  duck_path(@duck),
                  method: :delete,
                  data: { confirm: "Are you sure?" },
                  class: "btn btn-flat red" %>
        <% end %>
        <%= link_to "Back", ducks_path, class: "btn btn-ghost opac" %>
      </div>
    </div>
    <% if @duck.photo.attached? %>
      <div class="show-photo">
        <%= cl_image_tag @duck.photo.key, width: 400, height: 400, crop: :fill %>
      </div>
    <% else %>
      <div class="card-photo">
          <%= image_tag "logo.png", width: 400, height: 400, crop: :fill %>
      </div>
    <% end %>
  </div>
</div>