config/routes.rb
Rails.application.routes.draw do
  root to: 'ducks#index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :ducks do
    resources :rentals
  end
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  belongs_to :duck
  validates :date_start, :date_end, presence: true
  validate :date_end_after_date_start
  # validates :rating, numericality: true#, comparison: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }

  def date_end_after_date_start
    return if date_end.blank? || date_start.blank?

    if date_end < date_start
      errors.add(:date_end, "must be after the start date")
    end
  end

  def rental_available?(duck)
    @rentals = duck.rentals
    output = true
    @rentals.each do |rental|
      if rental.date_end > date_start && rental.date_start < date_start
        errors.add(:date_start, "Sorry, not available from #{rental.date_start.strftime("%d/%m/%Y")} to #{rental.date_end.strftime("%d/%m/%Y")}")
        output = false
      elsif rental.date_end > date_end && rental.date_start < date_end
        errors.add(:date_end, "Sorry, not available from #{rental.date_start.strftime("%d/%m/%Y")} to #{rental.date_end.strftime("%d/%m/%Y")}")
        output = false
      elsif rental.date_end <= date_end && rental.date_start >= date_start
        errors.add(:date_end, "Sorry, not available from #{rental.date_start.strftime("%d/%m/%Y")} to #{rental.date_end.strftime("%d/%m/%Y")}")
        output = false
      end
    end
    output
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_rental, only: [:show, :edit, :update, :destroy]

  def index
    @rentals = policy_scope(Rental).where(user_id: current_user)
  end

  def new
    @duck = Duck.find(params[:duck_id])
    @rental = Rental.new
    authorize @rental
  end

  def create
    @rental = Rental.new(rental_params)
    @rental.user = current_user
    @duck = Duck.find(params[:duck_id])
    @rental.duck = @duck
    authorize @rental
    if @rental.rental_available?(@duck) && @rental.save
      redirect_to duck_rentals_path
    else
      render :new
    end
  end

  def show
  end

  def edit
    authorize @rental
  end

  def update
    @rental = Rental.find(params[:id])
    @rental.update(rental_params)
    @duck = Duck.find(params[:duck_id])
    if @duck.rentals.empty?
      @duck.average_rating = @rental.rating
    else
      sum = 0.0
      length = 0.0
      @duck.rentals.each do |rental|
        if rental.rating.instance_of?(BigDecimal)
          sum += rental.rating
          length += 1
        end
      end
      @duck.average_rating = (sum / length)
      @duck.save
    end
    authorize @rental
    if @rental.save
      redirect_to duck_rentals_path
    else
      render :edit
    end
  end

  def destroy
    @rental = Rental.find(params[:id])
    authorize @rental
    if @rental.destroy
      redirect_to duck_rentals_path
    else
      redirect_to duck_rental_path
    end
  end

  private

  def rental_params
    params.require(:rental).permit(:date_start, :date_end, :comments, :rating, :user_id, :duck_id)
  end

  def set_rental
    @rental = Rental.find(params[:id])
    @duck = Duck.find(params[:duck_id])
  end
end

app/views/rentals/edit.html.erb
<div class="container">
  <h2>Add a comment and rating for the following reservation:</h2>
  <p><%= @rental.duck.name %></p>
  <p>Owner: <%= @rental.duck.user.username %></p>
  <p>from: <%= @rental.date_start.strftime("%d/%m/%Y") %></p>
  <p>to: <%= @rental.date_end.strftime("%d/%m/%Y") %></p>
  <%= simple_form_for [@duck, @rental] do |f| %>
    <%= f.input :comments %>
    <%= f.input :rating %>
    <%= f.submit "Send the comment", class: "btn btn-flat" %>
  <% end %>
  <br>
  <%= link_to "Back to rentals", duck_rentals_path, class: "btn btn-flat"%>
</div>

app/views/rentals/index.html.erb
<div class="container">
  <div class="cards">
    <% @rentals.each do |rental| %>
      <div class="card">
        <div class="card-row" style="height: auto">
          <%= cl_image_tag rental.duck.photo.key, height: 80, crop: :fill, class: "img rounded cover img-fluid" %>
          <h2><%= rental.duck.name %></h2>
          <p><%= rental.rating %>/5</p>
        </div>
        <div class="card-row">
          <p><strong>From: </strong><%= rental.date_start.strftime("%d/%m/%Y") %></p>
          <p><strong>To: </strong><%= rental.date_end.strftime("%d/%m/%Y") %></p>
        </div>
        <div class="card-row">
          <% days = (rental.date_end - rental.date_start) / (24 * 60 * 60) %>
          <p><strong>Duration: </strong><%= days.round %> days</p>
          <p><strong>Total price: </strong><%= (days * rental.duck.price).round %> Euros</p>
        </div>
        <div class="card-row" style="height: 80px;overflow: hidden;max-width: 450px;text-align: left">
          <p><%= rental.comments %></p>
        </div>
        <div class="card-row">
          <%= link_to 'Add a comment', edit_duck_rental_path(rental.duck, rental), class: "btn btn-ghost" %>
          <%= link_to 'Cancel rental',
                duck_rental_path(rental.duck, rental),
                method: :delete,
                data: { confirm: "Are you sure?" },
                class: "btn btn-ghost"  %>
        </div>
      </div>
    <% end %>
  </div>
  <br>
  <%= link_to "Back to ducks", ducks_path, class: "btn btn-flat" %>
</div>

app/views/rentals/new.html.erb
<div class="container">
  <h2>Rental request for:</h2>
  <h3><%= @duck.name %></h3>
  <div class="alert"><%= @message %></div>
  <p>Daily price for <%= @duck.name %>: <%= @duck.price.round %> €</p>
    <%= simple_form_for [@duck, @rental] do |f| %>
      <p>From</p><%= f.input :date_start, as: :date, html5: true, label: false %>
      <p>To</p><%= f.input :date_end, as: :date, html5: true, label: false %>
      <%= f.submit "Confirm", class: "btn btn-flat" %>
    <% end %>
  <br>
  <%= link_to "Back to my rentals", duck_rentals_path, class: "btn btn-flat"%>
</div>

app/views/rentals/show.html.erb
<div class="container">
  <h2><%= @rental.duck.name %></h2>
  <p>Owner: <%= @rental.duck.user.username %></p>
  <p><%= @rental.id %></p>
  <p>From:<%= @rental.date_start.strftime("%d/%m/%Y") %></p>
  <p>To:<%= @rental.date_end.strftime("%d/%m/%Y") %></p>
  <p><%= @rental.comments %></p>
</div>
<%= link_to "Back to rentals", duck_rentals_path, class: "btn btn-flat"%>
<%= link_to "Back to ducks", ducks_path, class: "btn btn-flat"%>
<%= link_to "Home", root_path, class: "btn btn-flat"%>